version: '{branch}/{build}'
image: Visual Studio 2019
configuration: Release
platform: x64
install:
- ps: ".\\tools\\install_sdk.ps1"
- cmd: >-
    if defined APPVEYOR_REPO_TAG_NAME (set SHVDN_VERSION_TAG=%APPVEYOR_REPO_TAG_NAME%) else (for /f %%i in ('git describe --abbrev^=0 --tags') do set SHVDN_VERSION_TAG=%%i)

    set SHVDN_VERSION=%SHVDN_VERSION_TAG:~1%

    echo Version: "%SHVDN_VERSION%"

build:
  project: ScriptHookVDotNet.sln
  publish_nuget: true
  parallel: true
  verbosity: minimal
before_package:
- cmd: >-
    del bin\Release\ScriptHookVDotNet*.metagen

    type README.md | more /P > bin\Release\README.txt

    type LICENSE.txt | more /P > bin\Release\LICENSE.txt

    echo ReloadKey=None > bin\Release\ScriptHookVDotNet.ini

    echo ConsoleKey=F4 >> bin\Release\ScriptHookVDotNet.ini

test: off
artifacts:
- path: bin/Release/
  name: ScriptHookVDotNet
