 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default
    
     steps:
       - checkout
       - run: tools/install_sdk.ps1
       - run: msbuild ScriptHookVDotNet.sln /t:Build /p:Configuration=Release
       - run: powershell Compress-Archive bin\Release\* scripthookvdotnet_debug.zip
       - store_artifacts:
          path: scripthookvdotnet_debug.zip
